Writing this site required a ton of distillation of so many valuable ideas I've come accross through other resources. I've attempted to extract the essense without loosing the core idea but naturally there is still ton to be explored on each topic in depth. To provide you good jumpng off points I've compiled a list of some of the most useful books and resources I know of to help you dive deep into the topics we have covered here.

- [_The Effective Executive – Peter Drucker_](https://bookshop.org/p/books/the-effective-executive-the-definitive-guide-to-getting-the-right-things-done-peter-f-drucker/6438957?ean=9780060833459) If you read just one business book in your life it should be this o
- ne. I read it at least once a year and every time I get something new and valuable from it.
- [_The Manager Tools and Career Tools podcasts_](https://manager-tool.com) These are immensely valuable and cover every topic you could want in a professional setting. They know everything I do and a whole lot more.
- [_The Minto Pyramid Principle – Barbra Minto_](https://www.barbaraminto.com/textbook.html) THE book on improving your writing. She sells it new on her website. It is not cheap so if cost is an issue, then used copies can be found fairly easily.
- [_Getting Things Done – David Allen_](https://www.barbaraminto.com/textbook.html) The bible of productivity. Allen’s work has been fundamental to my ability to manage my time and I am forever grateful for it.
- [_Effective Presentation – Ros Jay & Anthony Jay_](https://isbnsearch.org/isbn/0273688030) A great overview of the fundamentals of presenting.
- [_People Smart – Tony Alessandra Ph. D., and Michael J. O’Connor Ph.D._](https://bookshop.org/p/books/people-smart-powerful-techniques-for-turning-every-encounter-into-a-mutual-win-tony-alessandra/12441914?ean=9780962516115) A deep dive on DISC.
- [_How to Read a Book – Mortimer J Adler_](https://bookshop.org/p/books/how-to-read-a-book-revised-and-updated-mortimer-j-adler/1408400?ean=9780671212094) As the title implies it is an in-depth guide to reading to gain a deep understanding and read more critically.
- [_Good Strategy Bad Strategy: The Difference and Why It Matters – Richard Rumelt_](https://bookshop.org/p/books/good-strategy-bad-strategy-the-difference-and-why-it-matters-richard-rumelt/9791956?ean=9780307886231). This is everything you will ever need to know about strategy.
- [_The Go Giver: A Little Story about a Powerful Business Idea – Bob Burg and John David Mann_](https://bookshop.org/p/books/the-go-giver-expanded-edition-a-little-story-about-a-powerful-business-idea-go-giver-book-1-bob-burg/7680879?ean=9781591848288) A quick narrative read that talks about the power of giving.
- [_Love is the Killer App: How to Win Business and Influence Friends – Tim Sanders_](https://bookshop.org/p/books/love-is-the-killer-app-how-to-win-business-and-influence-friends-tim-sanders/7837458?ean=9781400046836) A quirky read but does an excellent job of talking about the value of giving and building a strong network of friends.
- [_How to Take Smart Notes: One Simple Technique to Boost Writing, Learning and Thinking - Sönke Ahrens_](https://bookshop.org/p/books/how-to-take-smart-notes-one-simple-technique-to-boost-writing-learning-and-thinking-sonke-ahrens/18400756?ean=9783982438801) A primer on the power of Zettelkasten.
- [_Andy Matushak - Evergreen Notes_](https://notes.andymatuschak.org/Evergreen_notes)_ The best example of a reference system.
- [_Building a Second Brain – Tiago Forte_](https://bookshop.org/p/books/building-a-second-brain-a-proven-method-to-organize-your-digital-life-and-unlock-your-creative-potential-tiago-forte/18265370?ean=9781982167387) A similar approach to Zettelkasten with some good examples and deatails on the benefits of such a system.
- [_The Coaching Habit: Say Less, Ask More & Change the Way You Lead Forever - Michael Bungay Stanier_](https://bookshop.org/p/books/the-coaching-habit-say-less-ask-more-change-the-way-you-lead-forever-michael-bungay-stanier/17315881?ean=9780978440749) A quick little book about the power of asking good questions.
- [_Crucial Conversations: Tools for Talking When Stakes Are High_ - Joseph Grenny, Kerry PAtterson, Ron McMillan, Al Switzler, Emily Gregory](https://bookshop.org/p/books/crucial-conversations-tools-for-talking-when-stakes-are-high-emily-gregory/17346582?ean=9781260474183) An in depth look at communication around difficult topics and building psycological safety.
- [_First Break All the Rules: What the World's Greatest Managers Do Differently_ - Gallup](https://bookshop.org/p/books/first-break-all-the-rules-what-the-world-s-greatest-managers-do-differently-gallup/594575?ean=9781595621115) Learn to build on your strengths rather than trying to eliminate your weaknesses.